# Generated by Django 3.2.8 on 2021-10-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211021_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magnus_Library_User',
            new_name='Hotel_User',
        ),
    ]
